 #### Matrix

In [5]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])

print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [7]:
var1 = np.array([[1,2,3],[4,5,6]])
print(var)
print(type(var1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
#addition
var = np.matrix([[1,2,3],[4,5,6]])
var2 = np.matrix([[1,2,3],[4,5,6]])
print(var +var2)

[[ 2  4  6]
 [ 8 10 12]]


In [20]:
#multipilication
var = np.matrix([[1,2],[4,5]])
var2 = np.matrix([[1,2],[4,5]])
print(var*var2)


print("using dot we can write in this way")
print(var.dot(var2))

[[ 9 12]
 [24 33]]
using dot we can write in this way
[[ 9 12]
 [24 33]]
